version: "2"
services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - thagomizer
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./resources/public/:/var/www/thagomizer/resources/public/
            - /etc/letsencrypt/live/thethagomizer.com/:/etc/letsencrypt/live/thethagomizer.com/
            - /etc/letsencrypt/archive/thethagomizer.com/:/etc/letsencrypt/archive/thethagomizer.com/
        networks:
            - thagomizer-network
        ports:
            - 80:80
            - 443:443
    redis:
        image: redis:latest
        container_name: redis
        networks:
            thagomizer-network:
                aliases:
                    - redis
        ports:
            - 6379:6379
    thagomizer:
        image: rbruehlman/thagomizer:latest
        container_name: thagomizer
        depends_on:
            - redis
        volumes:
            - ~/.aws/:/root/.aws/
        env_file:
            - .env
        networks:
            thagomizer-network:
                aliases:
                    - thagomizer
        ports:
            - 8000:8000

networks:
    thagomizer-network: